name: Chrome Extension Build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install Dependancies
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: sudo apt-get update
      - run: sudo apt-get install zip -y
      # - run: yarn install
      # - run: ls
      # - run: yarn build
      - run: ls -la
      - run: zip --version
      - name: Package Chrome Extension
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'obfuscate-adobe.cxr'
          path: './build'
      - run: echo "Created the packed CXR"
      - name: Zipped Chrome Extension
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'obfuscate-adobe.zip'
          path: './build'
      - run: echo "Created the packed ZIP"
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          body: 'Download either the .CXR and install directly into Chrome, or download the zip, unzip and load unpacked.'
          artifacts: './obfuscate-adobe.cxr,./obfuscate-adobe.zip'
          removeArtifacts: true
      - run: echo "🍏 This job's status is ${{ job.status }}."
